clc;
clear all;
noise=audioread('Alarm01.wav');
x=filter(1,[1,.5,0.33,.25],noise);
x=x(45904:50000);
a=lpc(x,3);
ex=filter([0,-a(2:end)],1,x);
e=x-ex;
[acs,lags]=xcorr(e,'coeff');
figure(1);
subplot(1,2,1);
plot(1:97,x(4001:4097),1:97,ex(4001:4097),'--');
title('original Signal Vs LPC Estimation');
xlabel('sample Number'); ylabel('Amplitude'); grid;
legend('orginal signal','LPC Estimate');
subplot(1,2,2);
plot(lags,acs);
title('Autocorrelaton of prediction Error');
xlabel('Lags'); ylabel('Normalized Value'); grid;